---
title: "diagnostics"
author: "Jeffrey Brennan"
date: "8/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)

library(tidyverse)
library(ggpubr)
```

# TS & RT Thresholds

```{r}

Plot_Threshold = function(df, criteria_name, plot_label) { 
  criteria_vals = subset(df, Date == maxdate) %>% 
    group_by(Date) %>% 
    do(data.frame(t(quantile(unlist(df[, criteria_name]), probs = c(0.4, 0.5, 0.6, 0.7, 0.8)))))

  criteria_features = merge(criteria_vals, df, by = 'Date')

  ggplot(subset(criteria_features, Date == maxdate), aes_string(y = 'County', x = criteria_name)) + 
  geom_point() + 
  geom_vline(xintercept = criteria_features$X40[1], color = 'red') +
  geom_vline(xintercept = criteria_features$X50.[1], color = 'orange') + 
  geom_vline(xintercept = criteria_features$X60.[1], color = 'green') + 
  geom_vline(xintercept = criteria_features$X70.[1], color = 'blue') + 
  geom_vline(xintercept = criteria_features$X80.[1], color = 'purple') + 
  labs(title = paste0(plot_label, ' by county quantile (Data from: ', maxdate-14, ')'),
       subtitle = paste0('40%: ', round(criteria_features$X40.[1], 2), ' | ',
                         '50%: ', round(criteria_features$X50.[1], 2), ' | ',
                         '60%: ', round(criteria_features$X60.[1], 2), ' | ',
                         '70%: ', round(criteria_features$X70.[1], 2), ' | ',
                         '80%: ', round(criteria_features$X80.[1], 2)),
       x = '', y ='') +
  facet_wrap(~TSA, scales = 'free') +
  ggpubr::theme_pubr(border = TRUE) +
  theme(axis.text.y = element_text(size = 5)) + 
  theme(axis.text.x = element_text(size = 6))
  ggsave(paste0('statistical-output/diagnostics/', plot_label, '.png'),
         width = 10, height = 10, dpi = 600)
  }

mydata = read.csv('tableau/county.csv')
mydata$Date = as.Date(mydata$Date)
maxdate = max(mydata$Date)
case_features = subset(mydata, Date >= maxdate-14) %>%
  group_by(County) %>%
  mutate(criteria1 = mean(Cases_Daily)) %>% 
  mutate(criteria2 = mean(Cases_Cumulative)) %>% 
  mutate(criteria3 = (mean(Cases_Cumulative) / Population_DSHS) * 1000)%>%
  mutate(criteria4 = max(Cases_Daily, na.rm = TRUE)) %>%
  mutate(criteria5 = median(Cases_Daily)) %>%
  dplyr::select(County, Date, PHR, TSA, contains('Criteria'))

Plot_Threshold(case_features, 'criteria1', 'mean(Cases_Daily)')
Plot_Threshold(case_features, 'criteria2', 'mean(Cases_Cumulative)')
Plot_Threshold(case_features, 'criteria3', 'mean(Cases_Cumulative) by Population_DSHS x 1000')
Plot_Threshold(case_features, 'criteria4', 'max(Cases_Daily)')
Plot_Threshold(case_features, 'criteria5', 'median(Cases_Daily)')
```


# DSHS VS HHS 

```{r}
state = readxl::read_excel('combined-datasets/state.xlsx', sheet = 1)

state_compare = state %>%
  mutate(Date = openxlsx::convertToDate(Date)) %>%
  dplyr::select(c(Date, grep('Hospitalizations_|Beds_', colnames(state)),
           HHS_Inpatient.Beds.Occupied.Estimated,
           HHS_Inpatient.Beds.Occupied.by.COVID.19.Patients.Estimated,
           HHS_ICU.Beds.Occupied.Estimated)) %>% 
  na.omit()

ggplot(state_compare, aes(x = Date)) + 
  geom_point(aes(y = Beds_Occupied_Total, color = 'DSHS'), size = 2) + 
  geom_point(aes(y = HHS_Inpatient.Beds.Occupied.Estimated, color = 'HHS Estimate'), size = 2) + 
  labs(y = 'Beds', title = 'Beds Occupied',
       subtitle = paste0('DSHS: Total Beds Occupied by Trauma Service Area\n',
                         'HHS: Estimated number of inpatient beds occupied for the given state and date')) +
  scale_color_manual('', values = c('blue', 'red'), labels = c('DSHS', 'HHS Estimate')) + 
  theme_pubr()

ggplot(state_compare, aes(x = Date)) + 
  geom_point(aes(y = Hospitalizations_General, color = 'DSHS'), size = 2) + 
  geom_point(aes(y = HHS_Inpatient.Beds.Occupied.by.COVID.19.Patients.Estimated, color = 'HHS Estimate'), size = 2) + 
  labs(y = 'Beds', title = 'COVID Beds Occupied', 
  subtitle = paste0('DSHS: Lab-Confirmed COVID-19 Hospitalized Patients (General) by Trauma Service Area (TSA)\n',
                    'HHS: Estimated number of inpatient beds occupied by COVID-19 patients')) + 
  scale_color_manual('', values = c('blue', 'red'), labels = c('DSHS', 'HHS Estimate')) + 
  theme_pubr()


ggplot(state_compare, aes(x = Date)) + 
  geom_point(aes(y = Beds_Occupied_ICU, color = 'DSHS'), size = 2) + 
  geom_point(aes(y = HHS_ICU.Beds.Occupied.Estimated, color = 'HHS Estimate'), size = 2) + 
  labs(y = 'Beds', title = 'ICU Beds Occupied',
       subtitle = paste0('DSHS: Total ICU Beds Occupied by Trauma Service Area (TSA)\n',
                         'HHS: Estimated number of ICU beds occupied for the given state and date')) + 
  scale_color_manual('', values = c('blue', 'red'), labels = c('DSHS', 'HHS Estimate')) + 
  theme_pubr()


ggplot(state_compare, aes(x = Date)) + 
  geom_point(aes(y = Beds_Occupied_ICU, color = 'DSHS'), size = 2) + 
  geom_point(aes(y = HHS_ICU.Beds.Occupied.Estimated, color = 'HHS Estimate'), size = 2) + 
  labs(y = 'Beds', title = 'ICU Beds Occupied',
       subtitle = paste0('DSHS: Total ICU Beds Occupied by Trauma Service Area (TSA)\n',
                         'HHS: Estimated number of ICU beds occupied for the given state and date')) + 
  scale_color_manual('', values = c('blue', 'red'), labels = c('DSHS', 'HHS Estimate')) + 
  theme_pubr()
```

# Hospitalization Investigation

```{r}
hosp = read.csv('tableau/hospitalizations_tsa.csv')
hosp$Date = as.Date(hosp$Date)

hosp_diagnostics = hosp %>%
  group_by(Date, TSA) %>%
  mutate(Hosp_manual_total = Hospitalizations_General + Hospitalizations_ICU) %>%
  mutate(Hosp_check = (Hosp_manual_total) == Hospitalizations_Total) %>% 
  mutate(Hosp_ratio = (Hosp_manual_total) / Hospitalizations_Total) %>%
  
  mutate(Capacity_Total = Beds_Available_Total + Beds_Occupied_Total) %>% 
  mutate(COVID_ratio_total1 = Hospitalizations_Total / Capacity_Total) %>% 
  mutate(COVID_ratio_total2 = (Hosp_manual_total) / Capacity_Total) %>% 
  mutate(Other_ratio_total1 = (Beds_Occupied_Total - Hospitalizations_Total) / Capacity_Total) %>% 
  mutate(Other_ratio_total2 = (Beds_Occupied_Total - Hosp_manual_total) / Capacity_Total) %>% 
  mutate(Available_ratio_total = Beds_Available_Total / Capacity_Total) %>% 
  mutate(ratio_check_total1 = COVID_ratio_total1 + Other_ratio_total1 + Available_ratio_total) %>%
  mutate(ratio_check_total2 = COVID_ratio_total2 + Other_ratio_total2 + Available_ratio_total) %>%
    
  mutate(Capacity_ICU = Beds_Available_ICU + Beds_Occupied_ICU) %>% 
  mutate(COVID_ratio_ICU = Hospitalizations_ICU / Capacity_ICU) %>% 
  mutate(Other_ratio_ICU = (Beds_Occupied_ICU - Hospitalizations_ICU) / Capacity_ICU) %>% 
  mutate(Available_ratio_ICU = Beds_Available_ICU / Capacity_ICU) %>%
  mutate(ratio_check_ICU = COVID_ratio_ICU + Other_ratio_ICU + Available_ratio_ICU)
```

## Covid Hospitalization Checking

```{r, fig.height=10, fig.width = 12}
ggplot(subset(hosp_diagnostics, !is.na(Hosp_check)),
       aes(x = Date)) +
  geom_point(aes(y = TSA)) + 
  labs(title = '(Hospitalizations_General + Hospitalizations_ICU) == Hospitalizations_Total') + 
  facet_wrap(~ Hosp_check, nrow = 2) +
  scale_x_date(date_labels = '%m/%d', breaks= 'days',
               limits = as.Date(c(min(hosp_diagnostics$Date), max(hosp_diagnostics$Date)))) +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = -90, size = 8))
```

```{r, fig.height=8, fig.width=10}
hosp_false = subset(hosp_diagnostics, Hosp_check == FALSE)

ggplot(hosp_false, aes(x = as.factor(Date), y = Hosp_ratio)) +
  geom_text(aes(label = round(Hosp_ratio, 2)), position = 'dodge') + 
  labs(title = '(Hospitalizations_General + Hospitalizations_ICU) / Hospitalizations_Total',
       subtitle = 'FALSE TSA only') + 
  facet_wrap(~ TSA) +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = -90, size = 8))
```

```{r}
subset(hosp_diagnostics, dplyr::near(ratio_check_total1, 1) == FALSE) %>%
  dplyr::select(c('Date', 'TSA', 'ratio_check_total1'))

subset(hosp_diagnostics, dplyr::near(ratio_check_total2, 1) == FALSE) %>%
  dplyr::select(c('Date', 'TSA', 'ratio_check_total1'))

subset(hosp_diagnostics, dplyr::near(ratio_check_ICU, 1) == FALSE) %>%
  dplyr::select(c('Date', 'TSA', 'ratio_check_total1'))
```

Spot checking

```{r}
hosp_diagnostics %>% filter(TSA == 'M' & Date == as.Date('2020-08-01')) %>%
  dplyr::select(c(Available_ratio_ICU, COVID_ratio_ICU, Other_ratio_ICU))

hosp_diagnostics %>% filter(TSA == 'M' & Date == as.Date('2020-08-01')) %>%
  dplyr::select(c(Beds_Available_ICU, Capacity_ICU, Hospitalizations_ICU, Beds_Occupied_ICU))
```

## ICU


```{r, fig.height=10, fig.width=8}
hosp_diagnostics %>% dplyr::filter(COVID_ratio_ICU < 0) %>% dplyr::select(contains('ICU'))
hosp_diagnostics %>% dplyr::filter(Available_ratio_ICU < 0) %>% dplyr::select(contains('ICU'))
```

### Negative other causes

```{r, fig.height=10, fig.width=8}
hosp_diagnostics %>% filter(Other_ratio_ICU < 0) %>% dplyr::select(contains('ICU')) %>% 
  ggplot(., aes(x = Date)) + 
  geom_point(aes(y = Hospitalizations_ICU, color = 'HOSP')) + 
  geom_point(aes(y = Beds_Occupied_ICU, color = 'OCC')) + 
  facet_wrap(~ TSA, scales = 'free') + 
  theme_pubr() + 
  scale_color_manual(values = c('HOSP' = 'blue', 'OCC' = 'red'),
                     labels = c('Hosp_ICU', 'Beds_Occupied_ICU')) +
  theme(axis.text.x = element_text(angle = -90))
```

## Total
### COVID Hosp > Capacity
```{r}
hosp_diagnostics %>% filter(COVID_ratio_total1 < 0 | COVID_ratio_total1 > 1) %>%
  dplyr::select(matches('Total|General')) %>%
  ggplot(., aes(x = Date)) + 
  geom_point(aes(y = Capacity_Total, color = 'blue')) + 
  geom_point(aes(y = Hospitalizations_Total, color = 'red')) + 
  facet_wrap(~ TSA, scales = 'free') + 
  theme_pubr() +
  scale_color_manual(values = c('blue', 'red'), labels = c('Capacity_Total', 'Hosp_Total')) +
  theme(axis.text.x = element_text(angle = -90))
```

### Negative other causes

```{r, fig.height=8, fig.width=8}
hosp_diagnostics %>% filter(Other_ratio_total1 < 0) %>%
  dplyr::select(matches('Total|General')) %>% 
  ggplot(., aes(x = Date)) + 
  geom_point(aes(y = Capacity_Total, color = 'CAP')) + 
  geom_point(aes(y = Hospitalizations_Total, color = 'HOSP')) + 
  geom_point(aes(y = Beds_Occupied_Total, color = 'OCC')) +
  facet_wrap(~ TSA, scales = 'free') + 
  theme_pubr() +
  scale_color_manual(values = c('CAP' = 'blue', 'HOSP' = 'red', 'OCC' = 'green'),
                     labels = c('Capacity_Total', 'Hosp_Total', 'Beds_Occupied_Total')) +
  theme(axis.text.x = element_text(angle = -90))

```

# VALIDATION

Builds validation text to be read by slack and outputted by slackbot

## setup
```{r}
county = read.csv('tableau/county.csv')
tsa = read.csv('tableau/hospitalizations_tsa.csv')
state = read.csv('tableau/stacked_demographics.csv')

date_out = ifelse((Sys.time() < as.POSIXct(paste0(Sys.Date(), '16:00'), tz = 'America/Chicago')),
                   Sys.Date() - 1,
                   Sys.Date())

data_urls = c('<https://dshs.texas.gov/coronavirus/TexasCOVID19DailyCountyCaseCountData.xlsx|CASES>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID19DailyCountyFatalityCountData.xlsx|DEATHS>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID-19CumulativeTestsOverTimebyCounty.xlsx|TESTS>',
              '<https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv|GOOGLE MOBILITY>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID-19HospitalizationsOverTimebyTSA.xlsx|TOTAL HOSPITALIZATIONS>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID-19HospitalizationsOverTimebyTSA.xlsx|ICU HOSPITALIZATIONS>',
              '<https://dshs.texas.gov/coronavirus/TexasHospitalCapacityoverTimebyTSA.xlsx|TOTAL CAPACITY>',
              '<https://dshs.texas.gov/coronavirus/TexasHospitalCapacityoverTimebyTSA.xlsx|ICU CAPACITY>',
              # '<https://apps.hhs.texas.gov/providers/directories/Texas_Nursing_Facilities_COVID_Summary.xls|NURSING FACILITIES>',
              # '<https://apps.hhs.texas.gov/providers/directories/Texas_Assisted_Living_Facilities_COVID_Summary.xls|ALF>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx|AGE>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx|GENDER>',
              '<https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx|RACE>')

calc_count_stats = function(daily_stat, df) { 
  
  # TODO: refactor to combine with demo component
  # get most recent data date where > 0 counties, TSAs etc report a valid value
  # some stats have missing values for smaller regions (including google mobility and lagged cases)
  latest_date = df %>%
    mutate(Date = as.Date(Date)) %>%
    group_by(Date) %>%
    mutate(nonzeros = !!as.name(daily_stat) > 0 & !is.na(!!as.name(daily_stat))) %>% 
    filter(sum(nonzeros) / length(nonzeros) > 0) %>%
    ungroup() %>%
    summarize(max(Date)) %>% 
    unlist() %>% 
    as.Date(origin = '1970-01-01')

  df = df %>%
    mutate(Date = as.Date(Date)) %>% 
    filter(Date <= latest_date)
  
  avg_df = df %>% 
    group_by(Date) %>% 
    summarize(Daily_Avg = mean(!!as.name(daily_stat), na.rm = TRUE)) %>%
    mutate(lag = Daily_Avg - lag(Daily_Avg))

  nonzeros = df %>%
    filter(Date == max(as.Date(df$Date))) %>% 
    summarize(!!as.name(daily_stat) > 0 & !is.na(!!as.name(daily_stat))) %>%
    unlist()
  
  stats = list(max(df[['Date']]),
               round(avg_df[['Daily_Avg']][nrow(avg_df)], 2),
               round(avg_df[['lag']][[nrow(avg_df)]], 2),
               round(sum(nonzeros) / length(nonzeros), 2) * 100)
  
  emojis = c(ifelse(stats[[1]] < date_out, ':warning:', ':heavy_check_mark:'),
             ifelse(stats[[2]] <= 0 | is.na(stats[2]), ':warning:', ':heavy_check_mark:'),
             ifelse(stats[[3]] <= 0 | is.na(stats[3]), ':warning:', ':heavy_check_mark:'),
             ifelse(stats[[4]] < 50 | is.na(stats[4]), ':warning:', ':heavy_check_mark:'))

  stats[[1]] = format(stats[[1]], '%Y-%m-%d')

  
  return(list(unlist(stats), emojis))
}

calc_demo_stats = function(group_text, df) {
  
  latest_date = df %>%
    mutate(Date = as.Date(Date)) %>%
    filter(Group_Type == group_text) %>%
    mutate(nonzeros = Cases_Daily > 0 & !is.na(Cases_Daily) & Deaths_Daily > 0 & !is.na(Deaths_Daily)) %>% 
    group_by(Date) %>%
    filter(sum(nonzeros) / length(nonzeros) > 0) %>% 
    ungroup() %>%
    summarize(max(Date)) %>% 
    unlist() %>% 
    as.Date(origin = '1970-01-01')
  
  df = df %>%
    mutate(Date = as.Date(Date)) %>% 
    filter(Date <= latest_date)

  avg_df = df %>% 
    dplyr::filter(Group_Type == group_text) %>%
    group_by(Date) %>%
    dplyr::select(Cases_Daily, Deaths_Daily) %>%
    summarize_all(mean) %>%
    mutate(case_lag = Cases_Daily - lag(Cases_Daily)) %>%
    mutate(death_lag = Deaths_Daily - lag(Deaths_Daily))

  
  stats = list(max(df[['Date']]),
               round(avg_df[['case_lag']][nrow(avg_df)], 2),
               round(avg_df[['death_lag']][nrow(avg_df)], 2))

  emojis = c(ifelse(stats[1] < date_out, ':warning:', ':heavy_check_mark:'),
             ifelse(stats[2] == 0 | is.na(stats[2]), ':warning:', ':heavy_check_mark:'),
             ifelse(stats[3] == 0 | is.na(stats[3]), ':warning:', ':heavy_check_mark:'))
    
  stats[[1]] = format(stats[[1]], '%Y-%m-%d')
  
  return(list(unlist(stats), emojis))
  }
```


## compute stats
```{r}
county_check = lapply(c('Cases_Daily', 'Deaths_Daily', 'Tests_Daily', 'Residential'), 
                      calc_count_stats, df = county)

tsa_check = lapply(c('Hospitalizations_Total', 'Hospitalizations_ICU', 'Beds_Available_Total', 'Beds_Available_ICU'),
                   calc_count_stats, df = tsa)

state_check = lapply(c('Age', 'Gender', 'Race'), calc_demo_stats, df = state)

# https://stackoverflow.com/questions/20428742/select-first-element-of-nested-list
stats_out = unlist(c(lapply(county_check, `[[`, 1),
                     lapply(tsa_check, `[[`, 1),
                     lapply(state_check, `[[`, 1)))

emojis_out = unlist(c(lapply(county_check, `[[`, 2),
                      lapply(tsa_check, `[[`, 2),
                      lapply(state_check, `[[`, 2)))
```

## organize stats
```{r}
# declare sublevels for use in creating validation df and renaming nested list output
county_sublevels = c('Cases', 'Deaths', 'Tests', 'Mobility')
tsa_sublevels = c('Hosp_Total', 'Hosp_ICU', 'Cap_Total', 'Cap_ICU')
state_sublevels = c('Age', 'Gender', 'Race')


validation_df = data.frame(Level = c(rep(c('County', 'TSA'), each = 16), rep('State', 9)),
                           Sublevel = c(rep(county_sublevels, each = 4),
                                        rep(tsa_sublevels, each = 4),
                                        rep(state_sublevels, each = 3)),
                           Emoji = emojis_out,
                           Text = c(rep(c('Latest date:', 'Average daily value:' ,
                                          'Average % change:', '% reporting > 0:'),
                                        times = length(unlist(c(county_check, tsa_check))) / 4 / 2),
                                rep(c('Latest Date', 'Average case change:', 'Average death change:'), times = 3)),
                       Statistic = stats_out) %>% 
  mutate_all(as.character)
```


## build slack text
```{r}
build_text = function(text_filters, data_url) { 
  # based on level and sublevel match, combined all despcriptive text and statistics into string separated by newlines ('\n')
  text_out = validation_df %>% 
    dplyr::filter(Level == text_filters[[1]] & Sublevel == text_filters[[2]]) %>%
    unite(combined, Emoji, Text, Statistic, sep = ' ') %>% 
    dplyr::select(combined) %>% 
    unlist() %>%
    paste0(collapse = '\n ')
    
  return(list(text = text_out, url = data_url))
}

# declare for combination into 'text_filters' list
level_text = c(head(rep(unique(validation_df$Level), each = 4), -1))
sublevel_text = c(unique(validation_df$Sublevel))

# obtain list of lists (~4 of 4)
validation_text = mapply(build_text, 
                         text_filters = mapply(list, level_text, sublevel_text, SIMPLIFY = FALSE),
                         data_urls,
                         SIMPLIFY = FALSE)
```

## final formatting

```{r}
library(jsonlite)
# convert to lists of list of lists (~3 of 4 of 4)
validation_out = list(County = validation_text[which(names(validation_text) == 'County')],
                      TSA = validation_text[which(names(validation_text) == 'TSA')],
                      State = validation_text[which(names(validation_text) == 'State')])

# rename repeated top level with correct sublevel for stat (mapply only supports list of lists natively)
names(validation_out$County) = county_sublevels
names(validation_out$TSA) = tsa_sublevels
names(validation_out$State) = state_sublevels

validation_json = toJSON(validation_out)
write(validation_json, file = 'statistical-output/diagnostics/validation.json')
```


# special requests

```{r, fig.height = 12, fig.width = 8}
demo = read.csv('original-sources/census/county_demo.csv')

demo_summary = demo %>% 
  filter(CTYNAME == 'Harris County' & YEAR == '11' & AGEGRP != 0) %>%
  mutate(AGEGRP_TEST = ifelse((AGEGRP %% 2) != 0, AGEGRP + 1, AGEGRP)) %>%
  group_by(AGEGRP_TEST) %>% 
  mutate_at(vars(8:ncol(demo)), funs(sum)) %>% 
  filter((AGEGRP %% 2) != 0) %>% 
  mutate(AGEGRP = dplyr::recode(AGEGRP,  `1` = '0-9', `3` = '10-19', `5` = '20-29',
                                `7` = '30-39', `9` = '40-49', `11` = '50-59',
                                `13` = '60-69', `15` = '70-79', `17` = '80+')) %>%
  gather('demographic', 'value', 9:ncol(demo)) %>% 
  mutate(demo_group = gsub('\\_.*', '', demographic)) %>%
  group_by(demo_group, AGEGRP) %>% 
  summarize(total = sum(value)) %>% 
  filter(demo_group %in% c('WA', 'BA', 'IA', 'AA', 'NA', 'NH', 'H')) %>% 
  mutate(demo_group = recode(demo_group, 'WA' = 'White', 'BA' = 'Black',
                             'IA' = 'American Indian & Alaska Native',
                             'AA' = 'Asian', 'NA' = 'Native Hawaiian & Pacific Islander',
                             'NH' = 'Not Hispanic', 'H' = 'Hispanic')) %>% 
  mutate(pct = prop.table(total))

write.csv(demo_summary, 'harris_demographics.csv', row.names = F)

ggplot(demo_summary, aes(x = AGEGRP, y = total, fill = demo_group)) + 
  geom_bar(stat = 'identity') +
  labs(title = 'Age X Race - Harris County') + 
  geom_text(aes(label = round(pct, 2))) + 
  facet_wrap(~demo_group, ncol = 1, scales = 'free') + 
  theme_pubr() + 
  theme(legend.position = 'right')


age_summary = demo %>%
  filter(CTYNAME == 'Harris County' & YEAR == '11' & AGEGRP != 0) %>%
  mutate(AGEGRP_TEST = ifelse((AGEGRP %% 2) != 0, AGEGRP + 1, AGEGRP)) %>%
  group_by(AGEGRP_TEST) %>% 
  mutate_at(vars(8:ncol(demo)), funs(sum)) %>% 
  filter((AGEGRP %% 2) != 0) %>% 
  mutate(AGEGRP = dplyr::recode(AGEGRP,  `1` = '0-9', `3` = '10-19', `5` = '20-29',
                                `7` = '30-39', `9` = '40-49', `11` = '50-59',
                                `13` = '60-69', `15` = '70-79', `17` = '80+')) %>% 
  dplyr::select(c(AGEGRP, TOT_POP))
```

```{r}
merged_county_out = read.csv('combined-datasets/county.csv') 
Q_df = merged_county_out %>%
  mutate(Date = as.Date(Date)) %>%
  dplyr::filter(Date == max(Date)) %>%
  dplyr::filter(TSA == 'Q') %>%
  dplyr::select(County, Population_DSHS, TSA) %>% 
  arrange(desc(Population_DSHS)) %>% 
  mutate(Q_POP = sum(Population_DSHS))
 
 Q_pop = Q_df$Q_POP[1]
 
TMC_df = merged_county_out %>%
  mutate(Date = as.Date(Date)) %>% 
  dplyr::filter(Date == max(Date)) %>%
  dplyr::filter(County %in% c('Austin', 'Brazoria', 'Chambers', 'Fort Bend', 'Galveston', 'Harris', 'Liberty', 'Montgomery', 'Waller')) %>%
  dplyr::select(County, Population_DSHS, TSA, Cases_Daily, Date) %>% 
  arrange(desc(Population_DSHS)) %>% 
  mutate(TMC_POP = sum(Population_DSHS))

TMC_pop = TMC_df$TMC_POP[1]


# ICU hospitalizations from TSA Q (8/31)
hosp_tsa = read.csv('combined-datasets/tsa.csv')
Q_ICU = hosp_tsa %>%
  mutate(Date = as.Date(Date)) %>%
  dplyr::filter(Date == as.Date('2020-09-06') & TSA == 'Q') %>%
  dplyr::select(Hospitalizations_ICU) %>% unlist()

# TMC dashboard value - 9/6
TMC_ICU = 78

# proposed TMC reporting and ICU share of surrounding 9 counties
TMC_coverage = 0.75

# 1.1 - Surrounding 9 county area has larger population than TSA Q
TMC_Q_ratio =  round(TMC_pop / Q_pop, 2)

# expected TSA Q hosp assuming above values are accurate
(TMC_ICU / TMC_coverage) / TMC_Q_ratio

# actual
Q_ICU

# actual TMC_coverage
round(TMC_ICU / Q_ICU, 2)
```

```{r}
merged_county_out %>% 
  filter(as.Date(Date) > as.Date('2020-09-01')) %>% 
  dplyr::filter(County %in% c('Austin', 'Brazoria', 'Chambers', 'Fort Bend', 'Galveston', 'Harris', 'Liberty', 'Montgomery', 'Waller')) %>% 
  group_by(Date) %>% 
  summarize(sum(Cases_Daily))

```

