bexar:
    data_type:     "vitals"
    county:        "Bexar"
    step_interval: 2000
    full_refresh:  true
    file_exists:   false
    col:
        metric_out: [ "cases_daily", "deaths_daily" ]
        input: [ "reporting_date", "case_count_weekly_change", "death_count_weekly_change" ]
        output: [ 'County', 'Date', 'cases_daily', 'deaths_daily' ]
        rename:
            reporting_date:            "Date"
            case_count_weekly_change:  "cases_daily"
            death_count_weekly_change: "deaths_daily"
        dtypes:
            reporting_date:            'int64[pyarrow]'
            case_count_weekly_change:  "int32[pyarrow]"
            death_count_weekly_change: "int32[pyarrow]"
        uid: [ 'Date' ]
    url:
        base:         'https://services.arcgis.com'
        owner:        "g1fRTDLeMgspWrYp"
        source_table: "Weekly_Bexar_County_CoVID19_Surveillance_Data_Public"
    out:
        dir:        "tableau/vitals/staging"
        table_name: "bexar_vitals"
harris:
    data_type:     "vitals"
    county:        "Harris"
    step_interval: 2000
    full_refresh:  true
    file_exists:   true
    col:
        metric_out: [ "cases_daily" ]
        filter:
            col:      'Source'
            operator: '=='
            value:    'HCTX'
        input: [ "Date", "Total", "Source" ]
        output: [ 'County', 'Date', 'cases_daily' ]
        rename:
            Date:  "Date"
            Total: "cases_daily"
        dtypes:
            Date:  'int64[pyarrow]'
            Total: "int32[pyarrow]"
        uid: [ 'Date' ]
    url:
        base:         'https://services.arcgis.com'
        owner:        "su8ic9KbA7PYVxPS"
        source_table: "Download_Reported_COVID_Cases_Timeline"
    out:
        dir:        "tableau/vitals/staging"
        table_name: "harris_vitals"
travis:
    data_type:     "vitals"
    county:        "Travis"
    step_interval: 2000
    full_refresh:  true
    file_exists:   true
    col:
        metric_out: [ "cases_cumulative", "deaths_cumulative" ]
        input: [ "Updated", "TotalCases", "TotalDeaths" ]
        output: [ 'County', 'Date', 'cases_cumulative', 'deaths_cumulative' ]
        rename:
            Updated:     "Date"
            TotalCases:  "cases_cumulative"
            TotalDeaths: "deaths_cumulative"
        dtypes:
            Updated:     'int64[pyarrow]'
            TotalCases:  "int32[pyarrow]"
            TotalDeaths: "int32[pyarrow]"
        uid: [ 'Date' ]
    url:
        base:         'https://services.arcgis.com'
        owner:        "0L95CJ0VTaxqcmED"
        source_table: "Daily_Count_COVID_view"
    out:
        dir:        "tableau/vitals/staging"
        table_name: "travis_vitals"
randall:
    data_type:     "vitals"
    county:        "Randall"
    step_interval: 1000
    full_refresh:  true
    file_exists:   true
    col:
        cases:
            metric_out: [ "cases_daily" ]
            filter:
                col:      'case_data_county'
                operator: '=='
                value:    'Randall'
            input: [ 'case_data_date_of_test', 'case_data_county', 'case_data_count' ]
            output: [ 'County', 'Date', 'cases_daily' ]
            rename:
                case_data_date_of_test: "Date"
                case_data_count:        "cases_daily"
            dtypes:
                case_data_date_of_test: 'int64[pyarrow]'
                case_data_count:        "int32[pyarrow]"
            uid: [ 'Date' ]
        deaths:
            metric_out: [ "deaths_daily" ]
            filter:
                col:      'death_data_county'
                operator: '=='
                value:    'Randall'
            input: [ 'death_data_date_of_death', 'death_data_county', 'death_data_count' ]
            output: [ 'County', 'Date',  'deaths_daily' ]
            rename:
                death_data_date_of_death: "Date"
                death_data_count:         "deaths_daily"
            dtypes:
                death_data_date_of_death: 'int64[pyarrow]'
                death_data_count:         "int32[pyarrow]"
            uid: [ 'Date' ]

    url:
        base:         'https://services6.arcgis.com'
        owner:        "Vdk8uHgdgYx8ZqS6"
        source_table: "public_health_dashboard_upload"
    out:
        dir:        "tableau/vitals/staging"
        table_name: "randall_vitals"
potter:
    data_type:     "vitals"
    county:        "Potter"
    step_interval: 1000
    full_refresh:  true
    file_exists:   true
    col:
        cases:
            metric_out: ["cases_daily"]
            filter:
                col:      'case_data_county'
                operator: '=='
                value:    'Potter'
            input: [ 'case_data_date_of_test', 'case_data_county', 'case_data_count' ]
            output: [ 'County', 'Date', 'cases_daily' ]
            rename:
                case_data_date_of_test: "Date"
                case_data_count:        "cases_daily"
            dtypes:
                case_data_date_of_test: 'int64[pyarrow]'
                case_data_count:        "int32[pyarrow]"
            uid: [ 'Date' ]
        deaths:
            metric_out: [ "deaths_daily" ]
            filter:
                col:      'death_data_county'
                operator: '=='
                value:    'Potter'
            input: [ 'death_data_date_of_death', 'death_data_county', 'death_data_count' ]
            output: [ 'County', 'Date',  'deaths_daily' ]
            rename:
                death_data_date_of_death: "Date"
                death_data_count:         "deaths_daily"
            dtypes:
                death_data_date_of_death: 'int64[pyarrow]'
                death_data_count:         "int32[pyarrow]"
            uid: [ 'Date' ]

    url:
        base:         'https://services6.arcgis.com'
        owner:        "Vdk8uHgdgYx8ZqS6"
        source_table: "public_health_dashboard_upload"
    out:
        dir:        "tableau/vitals/staging"
        table_name: "potter_vitals"
denton:
    data_type:     "vitals"
    county:        "Denton"
    step_interval: 2000
    full_refresh:  true
    file_exists:   true
    col:
        metric_out: [ "cases_daily", "deaths_daily" ]
        input: [ "DateOfObservation", "Total", "Deaths" ]
        output: [ 'County', 'Date', 'cases_daily', 'deaths_daily' ]
        rename:
            DateOfObservation: "Date"
            Total:             "cases_daily"
            Deaths:            "deaths_daily"
        dtypes:
            DateOfObservation: 'string'
            Total:             "int32[pyarrow]"
            Deaths:            "int32[pyarrow]"
        uid: [ 'Date' ]
        date_format: "%Y/%m/%d"
    url:
        base:              'https://services.arcgis.com'
        feature_server_id: 1
        owner:             "oTsZYNubyv7xK5yP"
        source_table:      "vDailyObservationsRT_WFL1"
    out:
        dir:        "tableau/vitals/staging"
        table_name: "denton_vitals"